apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hanin

type: Opaque
stringData:
  ADMIN_DEFAULT_PASSWORD: uVM7Xnx5wcu6p1t0
  JWT_SECRET: gu0z2eZW5LKjAqFfBKRsMe0NPvibVwQ5cEYw7QidA9BXbAAGu350ZlxQsBlVwLcF


