apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hanin-praxis-form-tls
  namespace: hanin
spec:
  secretName: hanin-praxis-form-tls
  dnsNames:
    - hanin.praxis-form.de
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: praxis-form-letsencrypt-prod
  usages:
    - digital signature
    - key encipherment