apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }} #secret to pull img
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repo}}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: MONGODB_URI
            value: mongodb://praxis-form-mongodb.praxis.svc.cluster.local:27017/praxis-hanin
          - name: ADMIN_DEFAULT_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: backend-secret
                    key: ADMIN_DEFAULT_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: JWT_SECRET
          - name: JWT_EXP_MINUTES
            value: "120"
        ports:
        - containerPort: 8080
