apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repo }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: API_URL
            value: {{ .Values.frontend.apiUrl }}
        ports:
        - containerPort: 80
