apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYWgyMDU4IiwicGFzc3dvcmQiOiJnaHBfTG1mSkZSbUZkV3hGRnVUYmVBS2JMQkhrWmpEZ1BiMENROHVvIiwiYXV0aCI6IllXZ3lNRFU0T21kb2NGOU1iV1pLUmxKdFJtUlhlRVpHZFZSaVpVRkxZa3hDU0d0YWFrUm5VR0l3UTFFNGRXOD0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
